import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowDownRight, ArrowUpRight, Camera, Menu, Search, ShoppingBag, X } from 'lucide-react'
import './styles.css'
const categories = [
  { name: 'Necklaces', note: 'SIGNATURE CHAINS', image: 'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=900&q=85' },
  { name: 'Bracelets', note: 'WRIST STORIES', image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=900&q=85' },
  { name: 'Rings', note: 'MARK YOUR OWN', image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=85' },
  { name: 'Accessories', note: 'THE FINISHING TOUCH', image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=85' },
]
function Logo() { return <a className="logo" href="#top" aria-label="STYX home"><img className="logo-image" src="/styx-logo.svg" alt="STYX" /></a> }
function Navbar() { const [menuOpen, setMenuOpen] = useState(false); return <header className="nav-wrap"><nav className="navbar" aria-label="Main navigation"><Logo /><div className={menuOpen ? 'nav-links is-open' : 'nav-links'}>{['Home', 'Shop', 'Collections', 'About'].map((link) => <a href={'#' + link.toLowerCase()} key={link} onClick={() => setMenuOpen(false)}>{link}</a>)}</div><div className="nav-actions"><button className="icon-button" aria-label="Search"><Search size={19} strokeWidth={1.5} /></button><button className="icon-button bag-button" aria-label="Shopping bag"><ShoppingBag size={19} strokeWidth={1.5} /><small>0</small></button><button className="icon-button menu-button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div></nav></header> }
function Hero() { return <section className="hero" id="top"><div className="hero-image" role="img" aria-label="Minimal silver necklace on a dark surface" /><div className="hero-shade" /><div className="hero-content page-pad"><p className="eyebrow reveal">EST 2024 <span /> COPENHAGEN / EVERYWHERE</p><h1 className="hero-title reveal delay-1">STREET<br /><em>LUXURY</em></h1><p className="hero-copy reveal delay-2">Sculptural pieces considered with care<br />Made for the moments between words</p><div className="hero-buttons reveal delay-3"><a className="button button-light" href="#shop">Shop collection <ArrowUpRight size={15} /></a><a className="text-link" href="#about">Explore STYX <ArrowDownRight size={15} /></a></div></div><div className="hero-index">01 <span /> 04</div><a className="scroll-cue" href="#categories">Scroll to discover <ArrowDownRight size={15} /></a></section> }
function SectionHeading({ kicker, title, action }) { return <div className="section-heading"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div>{action && <a className="text-link" href="#shop">{action} <ArrowUpRight size={15} /></a>}</div> }
function Categories() { return <section className="section page-pad categories" id="categories"><SectionHeading kicker="01 / THE EDIT" title={<>Find your<br /><em>signature</em></>} action="View all pieces" /><div className="category-grid">{categories.map((category, index) => <a className="category-card" href="#shop" key={category.name}><div className="category-image"><img src={category.image} alt="" loading="lazy" /><span>0{index + 1}</span></div><div className="category-meta"><div><p>{category.note}</p><h3>{category.name}</h3></div><ArrowUpRight size={19} /></div></a>)}</div></section> }
function Statement() { return <section className="statement page-pad" id="about"><img className="statement-star" src="/gold-star.svg" alt="" /><div className="statement-copy"><p className="eyebrow">03 / A POINT OF VIEW</p><h2>NOT MADE<br /><em>FOR EVERYONE</em></h2><p>STYX exists for those who choose their own direction Quiet confidence Distinct identity No unnecessary noise</p><a className="text-link" href="#footer">Read our story <ArrowUpRight size={15} /></a></div></section> }
function CollectionBanner() { return <section className="collection-banner"><div className="collection-image" /><div className="collection-shade" /><div className="collection-content page-pad"><p className="eyebrow">04 / NEW SEASON</p><h2>THE AFTER<br /><em>DARK COLLECTION</em></h2><a className="button button-outline" href="#shop">Discover collection <ArrowUpRight size={15} /></a></div><span className="collection-caption">A study in shadow &amp; light / 2024</span></section> }
function Newsletter() { return <section className="newsletter page-pad"><div><p className="eyebrow">STYX / PRIVATE ACCESS</p><h2>ENTER THE<br /><em>WORLD OF STYX</em></h2></div><div className="newsletter-form"><p>Get first access to new drops collections and stories</p><form onSubmit={(event) => event.preventDefault()}><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" placeholder="Your email address" /><button type="submit" aria-label="Join newsletter">Join <ArrowUpRight size={15} /></button></form><small>By subscribing you agree to our privacy policy</small></div></section> }
function Footer() { return <footer className="footer page-pad" id="footer"><div className="footer-top"><Logo /><p>Quiet pieces for<br />loud identities.</p><a className="back-top" href="#top">Back to top <ArrowUpRight size={15} /></a></div><div className="footer-links"><div><p className="eyebrow">Explore</p><a href="#shop">Shop</a><a href="#categories">Collections</a><a href="#about">About STYX</a></div><div><p className="eyebrow">Connect</p><a href="mailto:hello@styx.world">Contact</a><a href="#footer">Instagram</a><a href="#footer">Journal</a></div><div><p className="eyebrow">Information</p><a href="#footer">Terms</a><a href="#footer">Privacy</a><a href="#footer">Shipping</a></div></div><div className="footer-bottom"><span>© 2024 STYX WORLD</span><span>MADE FOR THOSE WHO MOVE DIFFERENTLY</span><Camera size={17} strokeWidth={1.5} /></div></footer> }
function App() { return <><Navbar /><main><Hero /><Categories /><Statement /><CollectionBanner /><Newsletter /></main><Footer /></> }
export default App
createRoot(document.getElementById('root')).render(<App />)
